export const successes = {
	continue: "continue",
	switching_protocols: "switching protocols",
	processing: "processing",
	earlyhints: "early hints",

	ok: "ok",
	created: "created",
	accepted: "accepted",
	non_authoritative_information: "non-authoritative information",
	no_content: "no content",
	reset_content: "reset content",
	partial_content: "partial content",
	multi_status: "multi-status",
	already_reported: "already reported",
	// im_used: "im used",

	// multiple_choices: "multiple choices",
	moved_permanently: "moved permanently",
	found: "found",
	see_other: "see other",
	not_modified: "not modified",
	// use_proxy: "use proxy",
	temporary_redirect: "temporary redirect",
	permanent_redirect: "permanent redirect",
};

export const errors = {
	bad_request: "bad request",
	unauthorized: "unauthorized",
	payment_required: "payment required",
	forbidden: "forbidden",
	not_found: "not found",
	method_not_allowed: "method not allowed",
	not_acceptable: "not acceptable",
	proxy_authentication_required: "proxy authentication required",
	request_timeout: "request timeout",
	conflict: "conflict",
	gone: "gone",
	length_required: "length required",
	precondition_failed: "precondition failed",
	payload_too_large: "payload too large",
	uri_too_long: "uri too long",
	unsupported_media_type: "unsupported media type",
	requested_range_not_satisfiable: "range not satisfiable",
	expectation_failed: "expectation failed",
	i_am_a_teapot: "i am a teapot",
	misdirected: "misdirected request",
	unprocessable_entity: "unprocessable entity",
	locked: "locked",
	failed_dependency: "failed dependency",
	// too_early: "too early",
	// upgrade_required: "upgrade required",
	precondition_required: "precondition required",
	too_many_requests: "too many requests",
	// request_header_fields_too_large: "request header fields too large",
	// unavailable_for_legal_reasons: "unavailable for legal reasons",

	internal_server_error: "internal server error",
	not_implemented: "not implemented",
	bad_gateway: "bad gateway",
	service_unavailable: "service unavailable",
	gateway_timeout: "gateway timeout",
	http_version_not_supported: "http version not supported",
	// variant_also_negotiates: "variant also negotiates",
	insufficient_storage: "insufficient storage",
	loop_detected: "loop detected",
	// not_extended: "not extended",
	// network_authentication_required: "network authentication required",
};
