// ── Core ────────────────────────────────────────────────────
export { BaseException } from "./core/baseException";
export type { TMiddleware, TNext, TExceptionArgs, TJoin } from "./core/types";
export { Exception } from "./core/exceptions";

// ── HTTP base ───────────────────────────────────────────────
export { HttpException } from "./http/base/HttpException";
export { ValidationErrorDto } from "./http/base/ValidationErrorDto";

// ── HTTP DTOs ───────────────────────────────────────────────
export { OkDto } from "./http/dtos/OkDto";
export { CreatedDto } from "./http/dtos/CreatedDto";
export { AcceptedDto } from "./http/dtos/AcceptedDto";
export { NoContentDto } from "./http/dtos/NoContentDto";
export { FoundDto } from "./http/dtos/FoundDto";
export { NotModifiedDto } from "./http/dtos/NotModifiedDto";
export { BadRequestDto } from "./http/dtos/BadRequestDto";
export { UnauthorizedDto } from "./http/dtos/UnauthorizedDto";
export { ForbiddenDto } from "./http/dtos/ForbiddenDto";
export { NotFoundDto } from "./http/dtos/NotFoundDto";
export { ConflictDto } from "./http/dtos/ConflictDto";
export { InternalServerErrorDto } from "./http/dtos/InternalServerErrorDto";
export { NotImplementedDto } from "./http/dtos/NotImplementedDto";
export { BadGatewayDto } from "./http/dtos/BadGatewayDto";
export { ServiceUnavailableDto } from "./http/dtos/ServiceUnavailableDto";
export { GatewayTimeoutDto } from "./http/dtos/GatewayTimeoutDto";
export { TooManyRequestsDto } from "./http/dtos/TooManyRequestsDto";
export { UnprocessableEntityDto } from "./http/dtos/UnprocessableEntityDto";
export { MethodNotAllowedDto } from "./http/dtos/MethodNotAllowedDto";
export { NotAcceptableDto } from "./http/dtos/NotAcceptableDto";
export { RequestTimeoutDto } from "./http/dtos/RequestTimeoutDto";
export { PayloadTooLargeDto } from "./http/dtos/PayloadTooLargeDto";
export { UnsupportedMediaTypeDto } from "./http/dtos/UnsupportedMediaTypeDto";
export { GoneDto } from "./http/dtos/GoneDto";
export { PreconditionFailedDto } from "./http/dtos/PreconditionFailedDto";
export { MisdirectedDto } from "./http/dtos/MisdirectedDto";
export { LockedDto } from "./http/dtos/LockedDto";
export { FailedDependencyDto } from "./http/dtos/FailedDependencyDto";
export { PreconditionRequiredDto } from "./http/dtos/PreconditionRequiredDto";
export { RequestedRangeNotSatisfiableDto } from "./http/dtos/RequestedRangeNotSatisfiableDto";
export { ExpectationFailedDto } from "./http/dtos/ExpectationFailedDto";
export { IAmATeapotDto } from "./http/dtos/IAmATeapotDto";
export { HttpVersionNotSupportedDto } from "./http/dtos/HttpVersionNotSupportedDto";
export { InsufficientStorageDto } from "./http/dtos/InsufficientStorageDto";
export { LoopDetectedDto } from "./http/dtos/LoopDetectedDto";
export { ContinueDto } from "./http/dtos/ContinueDto";
export { SwitchingProtocolsDto } from "./http/dtos/SwitchingProtocolsDto";
export { ProcessingDto } from "./http/dtos/ProcessingDto";
export { EarlyhintsDto } from "./http/dtos/EarlyhintsDto";
export { NonAuthoritativeInformationDto } from "./http/dtos/NonAuthoritativeInformationDto";
export { ResetContentDto } from "./http/dtos/ResetContentDto";
export { PartialContentDto } from "./http/dtos/PartialContentDto";
export { MultiStatusDto } from "./http/dtos/MultiStatusDto";
export { AlreadyReportedDto } from "./http/dtos/AlreadyReportedDto";
export { MovedPermanentlyDto } from "./http/dtos/MovedPermanentlyDto";
export { SeeOtherDto } from "./http/dtos/SeeOtherDto";
export { TemporaryRedirectDto } from "./http/dtos/TemporaryRedirectDto";
export { PermanentRedirectDto } from "./http/dtos/PermanentRedirectDto";
export { PaymentRequiredDto } from "./http/dtos/PaymentRequiredDto";
export { ProxyAuthenticationRequiredDto } from "./http/dtos/ProxyAuthenticationRequiredDto";
export { LengthRequiredDto } from "./http/dtos/LengthRequiredDto";
export { UriTooLongDto } from "./http/dtos/UriTooLongDto";
